INFLUX_USER = "influxUser"
INFLUX_PASS = "influxPassword"
INFLUX_ORG = "influxOrg"
INFLUX_BUCKET = "InfluxBucket"
INFLUX_URL = "http://localhost:8086"
INFLUX_TOKEN = "influxdb token"
RANDOM_ORG_KEY = "random.org key"