"""Public synthetic attribution contracts, not causal/private qualification."""

from .artifacts import read_attribution_artifact, write_attribution_artifact
from .contracts import (
    AttributionAmbiguityV1,
    AttributionBackgroundV1,
    AttributionEvidenceKind,
    AttributionFeatureShardV1,
    AttributionFeatureV1,
    AttributionGroupV1,
    AttributionReferenceV1,
    AttributionSnapshotV1,
    AttributionState,
    AttributionTaxonomyV1,
    AttributionValueV1,
    CAUSAL_NONCLAIM,
    ContributionV1,
    DecisionAttributionV1,
    ExplanationPlanV1,
    ExplainedOutputV1,
    ExplanationPolicyRegistryV1,
    ExplanationPolicyV1,
    FeatureSpace,
    GroupMethod,
    InteractionContributionV1,
    PolynomialTermV1,
    ReferenceModelV1,
    reference,
)
from .decisions import (
    DecisionStageV1,
    ReferenceDecisionPolicyV1,
    ReferenceDecisionV1,
    execute_reference_decision,
)
from .reference import evaluate_reference_model, explain_reference
from .registry import (
    AttributionExperimentLinkV1,
    AttributionRegistryV1,
    explanation_plan_fixture,
    reverse_attribution_dependencies,
)
from .taxonomy import attribution_feature_groups, resolve_attribution_taxonomy
from .mapping import (
    AttributionMappingV1,
    DiagonalFeatureMapV1,
    MappedAttributionV1,
)
from .interventions import (
    CounterfactualAttributionV1,
    NativeTriangleInterventionV1,
    TriangleInterventionScenarioV1,
    generate_triangle_fixture,
    make_triangle_intervention,
)
from .reports import (
    AttributionReportV1,
    AttributionStratumDifferenceV1,
    AttributionStratumReportV1,
    AttributionStratumV1,
    GroupImportanceV1,
    StratifiedAttributionV1,
    build_attribution_report,
    render_attribution_report,
)

__all__ = [
    "AttributionAmbiguityV1",
    "AttributionBackgroundV1",
    "AttributionEvidenceKind",
    "AttributionExperimentLinkV1",
    "AttributionFeatureShardV1",
    "AttributionFeatureV1",
    "AttributionGroupV1",
    "AttributionReferenceV1",
    "AttributionRegistryV1",
    "AttributionSnapshotV1",
    "AttributionState",
    "AttributionTaxonomyV1",
    "AttributionValueV1",
    "CAUSAL_NONCLAIM",
    "ContributionV1",
    "DecisionAttributionV1",
    "DecisionStageV1",
    "ExplanationPlanV1",
    "ExplainedOutputV1",
    "ExplanationPolicyRegistryV1",
    "ExplanationPolicyV1",
    "FeatureSpace",
    "GroupMethod",
    "InteractionContributionV1",
    "PolynomialTermV1",
    "ReferenceDecisionPolicyV1",
    "ReferenceDecisionV1",
    "ReferenceModelV1",
    "evaluate_reference_model",
    "execute_reference_decision",
    "explain_reference",
    "explanation_plan_fixture",
    "read_attribution_artifact",
    "reference",
    "reverse_attribution_dependencies",
    "write_attribution_artifact",
    "AttributionMappingV1",
    "AttributionReportV1",
    "AttributionStratumDifferenceV1",
    "AttributionStratumReportV1",
    "AttributionStratumV1",
    "CounterfactualAttributionV1",
    "DiagonalFeatureMapV1",
    "GroupImportanceV1",
    "MappedAttributionV1",
    "NativeTriangleInterventionV1",
    "StratifiedAttributionV1",
    "TriangleInterventionScenarioV1",
    "attribution_feature_groups",
    "build_attribution_report",
    "generate_triangle_fixture",
    "make_triangle_intervention",
    "render_attribution_report",
    "resolve_attribution_taxonomy",
]
