"""Data analytics operations for HistData artifacts."""

from __future__ import annotations

from histdatacom.data_analytics.feed_epochs import (
    DEFAULT_FEED_EPOCH_FEATURES,
    FEED_EPOCH_ASSIGNMENT_SCHEMA_VERSION,
    FEED_EPOCH_BOUNDARY_SCHEMA_VERSION,
    FEED_EPOCH_DEFINITION_SCHEMA_VERSION,
    FEED_EPOCH_EVIDENCE_SCHEMA_VERSION,
    FEED_EPOCH_FIT_CONFIG_SCHEMA_VERSION,
    FEED_EPOCH_INTERVAL_SCHEMA_VERSION,
    FEED_EPOCH_STABILITY_SCHEMA_VERSION,
    FeedEpochAssignmentV1,
    FeedEpochBoundaryV1,
    FeedEpochDefinitionV1,
    FeedEpochEvidenceV1,
    FeedEpochFitConfigV1,
    FeedEpochIntervalV1,
    FeedEpochStabilityV1,
    feed_epoch_definition_to_json,
    fit_feed_epochs,
    write_feed_epoch_definition,
)
from histdatacom.data_analytics.feed_regimes import (
    ANALYTICS_REPORT_SCHEMA_VERSION,
    AnalyticsDiscoveryResult,
    AnalyticsTarget,
    FeedPeriodProfile,
    FeedRegimeEra,
    FeedRegimeReport,
    analyze_feed_regimes,
    discover_analytics_targets,
    feed_regime_report_to_json,
    format_feed_regime_console_summary,
    write_feed_regime_report,
)

__all__ = [
    "ANALYTICS_REPORT_SCHEMA_VERSION",
    "AnalyticsDiscoveryResult",
    "AnalyticsTarget",
    "DEFAULT_FEED_EPOCH_FEATURES",
    "FEED_EPOCH_ASSIGNMENT_SCHEMA_VERSION",
    "FEED_EPOCH_BOUNDARY_SCHEMA_VERSION",
    "FEED_EPOCH_DEFINITION_SCHEMA_VERSION",
    "FEED_EPOCH_EVIDENCE_SCHEMA_VERSION",
    "FEED_EPOCH_FIT_CONFIG_SCHEMA_VERSION",
    "FEED_EPOCH_INTERVAL_SCHEMA_VERSION",
    "FEED_EPOCH_STABILITY_SCHEMA_VERSION",
    "FeedEpochAssignmentV1",
    "FeedEpochBoundaryV1",
    "FeedEpochDefinitionV1",
    "FeedEpochEvidenceV1",
    "FeedEpochFitConfigV1",
    "FeedEpochIntervalV1",
    "FeedEpochStabilityV1",
    "FeedPeriodProfile",
    "FeedRegimeEra",
    "FeedRegimeReport",
    "analyze_feed_regimes",
    "discover_analytics_targets",
    "feed_epoch_definition_to_json",
    "feed_regime_report_to_json",
    "fit_feed_epochs",
    "format_feed_regime_console_summary",
    "write_feed_epoch_definition",
    "write_feed_regime_report",
]
