"""Tiny newly generated IPC sources: no retained historical market evidence."""

from datetime import datetime, timezone

import polars as pl

from histdatacom.datasets import (
    DatasetCatalog,
    DatasetDescriptorV1,
    DatasetOrigin,
    HistDataProviderAdapter,
    build_observed_dataset_version,
    histdata_cache_path,
)
from histdatacom.orchestration.reconstruction import artifact_ref_for_file
from histdatacom.data_quality.training_contracts import TrainingSourceV1
from histdatacom.data_quality.training_weight_lineage import (
    TrainingWeightSourcePlanV1,
    WeightEvidenceKind,
)

SYMBOLS = ("EURGBP", "EURUSD", "GBPUSD")


def fixture_weight_source(
    directory,
    *,
    dates=("2010-01-04", "2010-01-05"),
    period="201001",
    step_seconds=5,
    include_end=True,
    crossed=False,
    duplicate=False,
    before_seconds=0,
    interior_duplicates=0,
):
    root = directory / "ASCII" / "T"
    for s, symbol in enumerate(SYMBOLS):
        times = []
        mids = []
        for d, day in enumerate(dates):
            start = (
                int(
                    datetime.fromisoformat(day)
                    .replace(tzinfo=timezone.utc)
                    .timestamp()
                )
                * 1000
            )
            seconds = [
                60,
                *range(
                    28800 + before_seconds,
                    29401 if include_end else 29400,
                    step_seconds,
                ),
                86340,
            ]
            if duplicate:
                seconds.insert(seconds.index(28800) + 1, 28800)
            if interior_duplicates:
                offset = seconds.index(28800 + 4 * step_seconds)
                seconds[offset:offset] = [seconds[offset]] * interior_duplicates
            times.extend(start + t * 1000 for t in seconds)
            mids.extend(
                1.0 + s * 0.2 + d * 0.01 + (i % 7) * 0.000001
                for i in range(len(seconds))
            )
        bids = [m - 0.0001 for m in mids]
        asks = [m + 0.0001 for m in mids]
        if crossed:
            bids[10] = asks[10] + 0.0001
        frame = pl.DataFrame(
            {
                "datetime": times,
                "bid": bids,
                "ask": asks,
                "vol": [777] * len(times),
            },
            schema={
                "datetime": pl.Int64,
                "bid": pl.Float64,
                "ask": pl.Float64,
                "vol": pl.Int32,
            },
        )
        path = histdata_cache_path(root, symbol, period)
        path.parent.mkdir(parents=True, exist_ok=True)
        frame.write_ipc(path)
    evidence = directory / "fixture-evidence.json"
    evidence.write_text('{"synthetic_contract_fixture":true}', encoding="utf-8")
    adapter = HistDataProviderAdapter()
    descriptor = DatasetDescriptorV1(
        "training-weight-contract-fixture",
        "Weight fixture",
        "Generated test quotes, never empirical qualification.",
        (DatasetOrigin.OBSERVED,),
    )
    version = build_observed_dataset_version(
        adapter,
        root,
        descriptor,
        symbols=SYMBOLS,
        periods=(period,),
        qualification_evidence=(
            artifact_ref_for_file(evidence, kind="synthetic-contract-fixture"),
        ),
    )
    catalog = DatasetCatalog(
        (adapter.provider,), (adapter.descriptor,), (descriptor,), (version,)
    )
    source = TrainingSourceV1(catalog.to_json(), version.dataset_version_id)
    plan = TrainingWeightSourcePlanV1(
        source,
        "application" if period == "201102" else "calibration",
        WeightEvidenceKind.FIXTURE,
    )
    return plan, version


def fixture_weight_model(directory, *, adapter_fingerprint="a" * 64):
    """A real small frozen TRAIN index backed by newly generated bytes."""
    from histdatacom.synthetic.motifs import (
        ReferenceMotifConditionV1,
        ReferenceMotifIndexConfigV1,
        ReferenceMotifSourceEventV1,
        ReferenceMotifSourceWindowV1,
        ReferenceMotifSplitKind,
        ReferenceMotifSplitV1,
        ReferenceMotifTransformPolicyV1,
        build_reference_motif_index,
    )
    from histdatacom.data_quality.training_weight_candidates import (
        read_training_weight_model,
    )

    directory.mkdir(parents=True, exist_ok=True)
    start = 1577952000000000000  # 2020-01-02, disjoint fixture TRAIN era.
    splits = tuple(
        ReferenceMotifSplitV1(
            kind, start + i * 1000000000000, start + (i + 1) * 1000000000000
        )
        for i, kind in enumerate(ReferenceMotifSplitKind)
    )
    windows = []
    for s, symbol in enumerate(SYMBOLS):
        bids = [1.0 + s * 0.2 + i * 0.00001 for i in range(8)]
        asks = [b + 0.0002 for b in bids]
        times = [start + i * 1_000_000_000 for i in range(8)]
        path = directory / f"{symbol}.data"
        pl.DataFrame(
            {
                "datetime": [t // 1_000_000 for t in times],
                "bid": bids,
                "ask": asks,
                "vol": [0] * 8,
            }
        ).write_ipc(path)
        condition = ReferenceMotifConditionV1(
            symbol=symbol,
            feed_epoch_id="technology_epoch_04",
            session_state="london",
            active_sessions=("london",),
            event_tags=("context:not-admitted",),
            metrics={
                "return_value": 0.0,
                "range_value": 0.001,
                "volatility": 0.0001,
                "spread": 0.0002,
                "tick_intensity": 1.0,
                "interarrival_ns": 1000000000.0,
                "timestamp_precision_ns": 1000000000.0,
                "price_precision_digits": 5.0,
                "source_quality_score": 1.0,
            },
        )
        events = tuple(
            ReferenceMotifSourceEventV1(t, i, b, a, i)
            for i, (t, b, a) in enumerate(zip(times, bids, asks), 1)
        )
        windows.append(
            ReferenceMotifSourceWindowV1(
                source_series_id="fixture:" + symbol,
                period="202001",
                source_artifact=artifact_ref_for_file(
                    path, kind="synthetic-contract-model-source"
                ),
                split_kind=ReferenceMotifSplitKind.TRAIN,
                condition=condition,
                events=events,
                first_known_at_ns=times[-1],
                available_at_ns=times[-1],
                transform_policy=ReferenceMotifTransformPolicyV1(
                    min_time_scale=0.001,
                    max_time_scale=1000.0,
                    min_price_scale=0.001,
                    max_price_scale=1000.0,
                    max_time_warp_ratio=1000.0,
                    allow_spread_scaling=True,
                ),
            )
        )
    index = build_reference_motif_index(
        windows,
        splits=splits,
        config=ReferenceMotifIndexConfigV1(min_cell_support=1),
    )
    index_path = directory / "index.json"
    index_path.write_text(index.to_json(), encoding="utf-8")
    return read_training_weight_model(
        index_path,
        evidence_kind=WeightEvidenceKind.FIXTURE,
        adapter_source_fingerprint=adapter_fingerprint,
    )
