"""Actual no-mkdir refusal at legacy writer entry/derived path boundaries.

These synthetic filesystem guards do not execute or qualify scientific models.
Poison values deliberately prove refusal before evidence/serializer work.
"""

import importlib
from pathlib import Path
from types import SimpleNamespace

import pytest

from histdatacom.managed_artifact_boundary import (
    MANAGED_ARTIFACT_MARKER,
    ManagedArtifactBoundaryError,
)

_DIRECTORY_WRITERS = (
    (
        "data_quality.training_weight_artifacts",
        "write_training_weight_candidate_shard",
    ),
    ("market_context.corpus", "write_market_context_corpus"),
    ("market_context.official_sources", "write_official_fetch_bundle"),
    ("market_context.positioning", "write_cftc_positioning_corpus"),
    (
        "synthetic.benchmark_corpus",
        "write_reverse_degradation_benchmark_corpus",
    ),
    ("synthetic.benchmark_corpus", "write_benchmark_window_metric_trace"),
    (
        "synthetic.benchmark_source_projection",
        "write_benchmark_source_projection_manifest",
    ),
    ("synthetic.motif_library", "write_modern_reference_motif_artifacts"),
    ("synthetic.projection_burden", "write_projection_burden_report"),
    ("synthetic.projection_burden", "write_projection_burden_release_coverage"),
)


def _module(name):
    return importlib.import_module("histdatacom." + name)


def _mark(path, kind="file"):
    path.mkdir(parents=True)
    marker = path / MANAGED_ARTIFACT_MARKER
    if kind == "file":
        marker.write_bytes(b"invalid but present marker")
    elif kind == "directory":
        marker.mkdir()
    else:
        marker.symlink_to("absent-marker-target")
    (path / "protected.bin").write_bytes(b"immutable generated bytes")
    return path


def _snapshot(root):
    return {
        path.relative_to(root).as_posix(): (
            ("link", str(path.readlink()))
            if path.is_symlink()
            else (
                ("directory", "")
                if path.is_dir()
                else ("file", path.read_bytes())
            )
        )
        for path in sorted(root.rglob("*"))
    }


@pytest.mark.parametrize("module_name,function_name", _DIRECTORY_WRITERS)
@pytest.mark.parametrize("marker_kind", ("file", "directory", "symlink"))
def test_directory_writer_refuses_before_mkdir_or_model_access(
    tmp_path, module_name, function_name, marker_kind
):
    writer = getattr(_module(module_name), function_name)
    protected = _mark(tmp_path / "managed", marker_kind)
    before = _snapshot(tmp_path)
    with pytest.raises(ManagedArtifactBoundaryError):
        writer(None, protected / "must-not-create" / "nested")
    assert _snapshot(tmp_path) == before


@pytest.mark.parametrize("module_name,function_name", _DIRECTORY_WRITERS)
def test_directory_writer_refuses_managed_alias_before_mkdir(
    tmp_path, module_name, function_name
):
    writer = getattr(_module(module_name), function_name)
    protected = _mark(tmp_path / "managed")
    alias = tmp_path / "ordinary-alias"
    alias.symlink_to(protected, target_is_directory=True)
    before = _snapshot(tmp_path)
    with pytest.raises(ManagedArtifactBoundaryError):
        writer(None, alias / "must-not-create")
    assert _snapshot(tmp_path) == before


@pytest.mark.parametrize("alias", (False, True))
@pytest.mark.parametrize(
    "module_name,function_name",
    (
        ("market_context.corpus", "write_market_context_corpus"),
        ("market_context.official_sources", "write_official_fetch_bundle"),
        ("market_context.positioning", "write_cftc_positioning_corpus"),
    ),
)
def test_market_writer_admits_actual_sources_child_before_evidence(
    tmp_path, module_name, function_name, alias
):
    root = tmp_path / "ordinary"
    root.mkdir()
    if alias:
        (root / "sources").symlink_to(
            _mark(tmp_path / "managed"), target_is_directory=True
        )
    else:
        _mark(root / "sources")
    before = _snapshot(tmp_path)
    with pytest.raises(ManagedArtifactBoundaryError):
        getattr(_module(module_name), function_name)(None, root)
    assert _snapshot(tmp_path) == before


@pytest.mark.parametrize("derived", (False, True))
def test_reconstruction_report_admits_derived_directory(tmp_path, derived):
    module = _module("orchestration.reconstruction")
    root = tmp_path / "reports"
    if derived:
        _mark(root / ".histdatacom" / module.RECONSTRUCTION_REPORT_DIRECTORY)
    else:
        _mark(root)
    before = _snapshot(tmp_path)
    with pytest.raises(ManagedArtifactBoundaryError):
        module.write_reconstruction_report(None, root)
    assert _snapshot(tmp_path) == before


@pytest.mark.parametrize(
    "kind", ("stage", "spec", "cftc-json", "benchmark-set", "diagnostics")
)
def test_other_writer_entries_refuse_before_mkdir_or_serializer(tmp_path, kind):
    root = _mark(tmp_path / "managed") / "must-not-create"
    before = _snapshot(tmp_path)
    with pytest.raises(ManagedArtifactBoundaryError):
        if kind == "stage":
            _module("orchestration.reconstruction")._write_stage_receipt(
                root / "receipt.json", None
            )
        elif kind == "spec":
            _module("synthetic.diagnostics").write_diagnostic_publication_spec(
                None, root / "spec.json"
            )
        elif kind == "cftc-json":
            _module("market_context.positioning")._write_json_artifact(
                root, "generated", "generated", {}, metadata={}
            )
        elif kind == "benchmark-set":
            _module(
                "synthetic.benchmark_corpus"
            ).write_reverse_degradation_benchmark_artifacts(
                None, None, None, root
            )
        else:
            _module("synthetic.diagnostics").publish_reconstruction_diagnostics(
                None, output_directory=root
            )
    assert _snapshot(tmp_path) == before


@pytest.mark.parametrize("target", ("json", "markdown", "receipt"))
def test_certification_preflights_all_three_outputs_before_any_mkdir(
    tmp_path, target
):
    module = _module("synthetic.certification")
    managed = _mark(tmp_path / "managed")
    json_path = tmp_path / "ordinary-json" / "report.json"
    markdown_path = tmp_path / "ordinary-markdown" / "report.md"
    if target == "json":
        json_path = managed / "new-json" / "report.json"
    elif target == "markdown":
        markdown_path = managed / "new-markdown" / "report.md"
    else:
        json_path.parent.mkdir()
        json_path.with_name(
            json_path.name + ".provider-policy.json"
        ).symlink_to(managed / "protected.bin")
    before = _snapshot(tmp_path)
    with pytest.raises(ManagedArtifactBoundaryError):
        module.write_reconstruction_certification_dossier(
            None, json_path=json_path, markdown_path=markdown_path
        )
    assert _snapshot(tmp_path) == before


def test_weight_component_set_preflight_precedes_replay_and_first_write(
    tmp_path, monkeypatch
):
    module = _module("data_quality.training_weight_artifacts")
    root = tmp_path / "ordinary"
    root.mkdir()
    managed = _mark(tmp_path / "managed")
    (root / "z-managed.json").symlink_to(managed / "protected.bin")
    monkeypatch.setattr(
        module,
        "_manifest",
        lambda _: (
            SimpleNamespace(to_json=lambda: "{}"),
            {"a-ordinary.json": b"ordinary", "z-managed.json": b"protected"},
        ),
    )

    def forbidden(*args, **kwargs):
        pytest.fail("model replay must not run before whole output admission")

    monkeypatch.setattr(
        module, "replay_training_weight_candidate_shard", forbidden
    )
    before = _snapshot(tmp_path)
    with pytest.raises(ManagedArtifactBoundaryError):
        module.write_training_weight_candidate_shard(None, root)
    assert _snapshot(tmp_path) == before


def test_unmanaged_json_leaf_keeps_ordinary_write_behavior(tmp_path):
    """A real primitive writer I/O control, not a CFTC scientific claim."""
    module = _module("market_context.positioning")
    root = tmp_path / "ordinary" / "new"
    ref = module._write_json_artifact(
        root, "generated", "generated", {"value": 1}, metadata={}
    )
    assert Path(ref.path).read_bytes() == b'{"value":1}\n'
    assert (
        module._write_json_artifact(
            root, "generated", "generated", {"value": 1}, metadata={}
        )
        == ref
    )


def test_weight_writer_preserves_manifest_bytes_after_component_loop(
    tmp_path, monkeypatch
):
    """Actual writer I/O with explicit serializer/replay doubles, not science."""
    module = _module("data_quality.training_weight_artifacts")
    manifest_json = '{"manifest":"generated-only-I/O-control"}'
    components = {"a.json": b"first component", "z.json": b"last component"}
    monkeypatch.setattr(
        module,
        "_manifest",
        lambda _: (SimpleNamespace(to_json=lambda: manifest_json), components),
    )
    replayed = []
    monkeypatch.setattr(
        module,
        "replay_training_weight_candidate_shard",
        lambda shard, *, approval: replayed.append((shard, approval)),
    )
    root = tmp_path / "ordinary"
    result = module.write_training_weight_candidate_shard(None, root)
    assert replayed == [(None, None)]
    assert result.read_bytes() == manifest_json.encode("ascii")
    for name, raw in components.items():
        assert (root / name).read_bytes() == raw
