"""Tests for local developer tool hook launchers."""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]
RUN_DEV_TOOL = REPO_ROOT / "scripts" / "run_dev_tool.py"


def test_run_dev_tool_resolves_venv_tool_without_ambient_path() -> None:
    """The hook launcher should not require venv/bin on ambient PATH."""
    env = os.environ.copy()
    env["HISTDATACOM_DEV_VENV"] = sys.prefix
    env["PATH"] = os.defpath
    result = subprocess.run(  # noqa:S603
        [sys.executable, str(RUN_DEV_TOOL), "coverage", "--version"],
        cwd=REPO_ROOT,
        env=env,
        capture_output=True,
        check=False,
        text=True,
    )

    assert result.returncode == 0
    assert "Coverage.py" in result.stdout


def test_run_dev_tool_remove_is_cross_platform(tmp_path: Path) -> None:
    """Coverage cleanup should not depend on a platform-specific rm binary."""
    artifact = tmp_path / ".coverage"
    artifact.write_text("coverage data", encoding="UTF-8")

    result = subprocess.run(  # noqa:S603
        [sys.executable, str(RUN_DEV_TOOL), "--remove", str(artifact)],
        cwd=REPO_ROOT,
        capture_output=True,
        check=False,
        text=True,
    )

    assert result.returncode == 0
    assert not artifact.exists()


def test_local_pre_commit_hooks_use_dev_tool_launcher() -> None:
    """Coverage should be one final pre-push hook after branch checks."""
    config = yaml.safe_load((REPO_ROOT / ".pre-commit-config.yaml").read_text())
    ordered_hooks = [
        hook for repo in config["repos"] for hook in repo.get("hooks", [])
    ]
    hooks = {hook["id"]: hook for hook in ordered_hooks}

    assert hooks["histdatacom"]["entry"] == (
        "scripts/run_dev_tool.py histdatacom"
    )
    assert not {
        "coverage-run",
        "coverage-combine",
        "coverage-report",
        "coverage-rm",
    }.intersection(hooks)
    coverage = hooks["coverage-final"]
    assert coverage["entry"] == "scripts/run_dev_tool.py python"
    assert coverage["args"] == [
        "scripts/run_final_coverage.py",
        "--ensure",
    ]
    assert coverage["pass_filenames"] is False
    assert coverage["always_run"] is True
    assert coverage["stages"] == ["pre-push"]
    hook_ids = [hook["id"] for hook in ordered_hooks]
    assert hook_ids.count("coverage-final") == 1
    assert hook_ids.index("commitizen-branch") < hook_ids.index(
        "coverage-final"
    )


def test_architecture_diagram_generation_is_pre_commit_gated() -> None:
    """Architecture SVGs should be regenerated by the local pre-commit loop."""
    config = yaml.safe_load((REPO_ROOT / ".pre-commit-config.yaml").read_text())
    hooks = {
        hook["id"]: hook
        for repo in config["repos"]
        if repo.get("repo") == "local"
        for hook in repo["hooks"]
    }

    diagram_hook = hooks["architecture-diagrams"]

    assert diagram_hook["entry"] == "scripts/run_dev_tool.py python"
    assert diagram_hook["args"] == ["tests/architecture/generate_diagrams.py"]
    assert diagram_hook["pass_filenames"] is False
    assert diagram_hook["always_run"] is True
    assert diagram_hook["stages"] == ["pre-commit"]
