"""Public orchestration client and job-control helpers."""

from __future__ import annotations

from histdatacom.sidecar.client import (
    CONTROL_ATTEMPTS_METADATA_KEY,
    CONTROL_EXECUTION_METADATA_KEY,
    DEFAULT_RUN_WORKFLOW_NAME,
    RUN_REQUEST_METADATA_KEY,
    TEMPORAL_EXECUTION_STATUS_METADATA_KEY,
    TEMPORAL_EXECUTION_STATUS_PREFIX,
    TEMPORAL_EXTRA_HINT,
    SidecarJobHandle as JobHandle,
    SidecarJobResult as JobResult,
    SidecarUnavailableError as OrchestrationUnavailableError,
    TemporalDependencyError as RuntimeDependencyError,
    cancel_job,
    cancel_job_sync,
    connect_temporal_client,
    get_job_artifacts,
    get_job_artifacts_sync,
    get_job_logs,
    get_job_logs_sync,
    get_job_progress,
    get_job_progress_sync,
    get_job_result,
    get_job_result_sync,
    inspect_job_status,
    inspect_job_status_sync,
    list_job_statuses,
    list_job_statuses_sync,
    list_stored_job_statuses,
    observe_workflow_result,
    resolve_sidecar_worker_config,
    resume_job,
    resume_job_sync,
    retry_job,
    retry_job_sync,
    run_request_payload,
    sidecar_job_store,
    sidecar_job_store_path,
    sidecar_job_store_root,
    submit_control_job,
    submit_control_job_sync,
    submit_run_request,
    submit_run_request_and_observe,
    submit_run_request_and_observe_sync,
    workflow_id_for_request,
)

resolve_worker_config = resolve_sidecar_worker_config
job_store = sidecar_job_store
job_store_path = sidecar_job_store_path
job_store_root = sidecar_job_store_root

__all__ = [
    "CONTROL_ATTEMPTS_METADATA_KEY",
    "CONTROL_EXECUTION_METADATA_KEY",
    "DEFAULT_RUN_WORKFLOW_NAME",
    "JobHandle",
    "JobResult",
    "OrchestrationUnavailableError",
    "RUN_REQUEST_METADATA_KEY",
    "RuntimeDependencyError",
    "TEMPORAL_EXECUTION_STATUS_METADATA_KEY",
    "TEMPORAL_EXECUTION_STATUS_PREFIX",
    "TEMPORAL_EXTRA_HINT",
    "cancel_job",
    "cancel_job_sync",
    "connect_temporal_client",
    "get_job_artifacts",
    "get_job_artifacts_sync",
    "get_job_logs",
    "get_job_logs_sync",
    "get_job_progress",
    "get_job_progress_sync",
    "get_job_result",
    "get_job_result_sync",
    "inspect_job_status",
    "inspect_job_status_sync",
    "job_store",
    "job_store_path",
    "job_store_root",
    "list_job_statuses",
    "list_job_statuses_sync",
    "list_stored_job_statuses",
    "observe_workflow_result",
    "resolve_worker_config",
    "resume_job",
    "resume_job_sync",
    "retry_job",
    "retry_job_sync",
    "run_request_payload",
    "submit_control_job",
    "submit_control_job_sync",
    "submit_run_request",
    "submit_run_request_and_observe",
    "submit_run_request_and_observe_sync",
    "workflow_id_for_request",
]
