"""Public orchestration resource and Temporal runtime provisioning helpers."""

from __future__ import annotations

from histdatacom.sidecar.resources import (
    DEFAULT_TEMPORAL_RUNTIME_DOWNLOAD_TIMEOUT_SECONDS,
    DEFAULT_TEMPORAL_RUNTIME_LOCK_POLL_SECONDS,
    DEFAULT_TEMPORAL_RUNTIME_LOCK_TIMEOUT_SECONDS,
    MANIFEST_FILENAME,
    TEMPORAL_CACHE_DIR_ENV,
    TEMPORAL_EXECUTABLE_ENV,
    TEMPORAL_OFFLINE_ENV,
    DownloadArchive,
    SidecarExecutableUnavailable as TemporalExecutableUnavailable,
    SidecarManifest as RuntimeManifest,
    SidecarPlatformResource as RuntimePlatformResource,
    SidecarResourceError as OrchestrationResourceError,
    TemporalRuntimeArtifact,
    TemporalRuntimeCacheEntry,
    TemporalRuntimeChecksumError,
    TemporalRuntimeIndex,
    TemporalRuntimeOfflineError,
    TemporalRuntimeProvisioningError,
    TemporalRuntimeResolution,
    UnsupportedSidecarPlatform as UnsupportedRuntimePlatform,
    current_platform_key,
    default_temporal_runtime_cache_dir,
    inspect_temporal_runtime_cache,
    load_sidecar_manifest,
    load_temporal_runtime_index,
    prune_temporal_runtime_cache,
    read_sidecar_asset_text,
    resolve_temporal_runtime_executable,
    sidecar_asset,
    sidecar_executable_path,
    sidecar_platform_resource,
    temporal_runtime_artifact,
    temporal_runtime_cache_entry_dir,
    temporal_runtime_executable_path,
)

runtime_asset = sidecar_asset
read_runtime_asset_text = read_sidecar_asset_text
load_runtime_manifest = load_sidecar_manifest
runtime_platform_resource = sidecar_platform_resource
packaged_temporal_executable_path = sidecar_executable_path

__all__ = [
    "DEFAULT_TEMPORAL_RUNTIME_DOWNLOAD_TIMEOUT_SECONDS",
    "DEFAULT_TEMPORAL_RUNTIME_LOCK_POLL_SECONDS",
    "DEFAULT_TEMPORAL_RUNTIME_LOCK_TIMEOUT_SECONDS",
    "DownloadArchive",
    "MANIFEST_FILENAME",
    "OrchestrationResourceError",
    "RuntimeManifest",
    "RuntimePlatformResource",
    "TEMPORAL_CACHE_DIR_ENV",
    "TEMPORAL_EXECUTABLE_ENV",
    "TEMPORAL_OFFLINE_ENV",
    "TemporalExecutableUnavailable",
    "TemporalRuntimeArtifact",
    "TemporalRuntimeCacheEntry",
    "TemporalRuntimeChecksumError",
    "TemporalRuntimeIndex",
    "TemporalRuntimeOfflineError",
    "TemporalRuntimeProvisioningError",
    "TemporalRuntimeResolution",
    "UnsupportedRuntimePlatform",
    "current_platform_key",
    "default_temporal_runtime_cache_dir",
    "inspect_temporal_runtime_cache",
    "load_runtime_manifest",
    "load_temporal_runtime_index",
    "packaged_temporal_executable_path",
    "prune_temporal_runtime_cache",
    "read_runtime_asset_text",
    "resolve_temporal_runtime_executable",
    "runtime_asset",
    "runtime_platform_resource",
    "temporal_runtime_artifact",
    "temporal_runtime_cache_entry_dir",
    "temporal_runtime_executable_path",
]
